export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST';
export const ADMIN_SIGNIN_REQUEST_STATUS = 'ADMIN_SIGNIN_REQUEST_STATUS';
export const ADMIN_SIGNIN_REQUEST_SUCCESS = 'ADMIN_SIGNIN_REQUEST_SUCCESS';
export const ADMIN_SIGNIN_REQUEST_FAIL = 'ADMIN_SIGNIN_REQUEST_FAIL';
export const ADMIN_SIGNIN_RESET_STATE = 'ADMIN_SIGNIN_RESET_STATE';

export const ADMIN_ADD_ITEM_REQUEST = 'ADMIN_ADD_ITEM_REQUEST';
export const ADMIN_ADD_ITEM_REQUEST_STATUS = 'ADMIN_ADD_ITEM_REQUEST_STATUS';
export const ADMIN_ADD_ITEM_REQUEST_SUCCESS = 'ADMIN_ADD_ITEM_REQUEST_SUCCESS';
export const ADMIN_ADD_ITEM_REQUEST_FAIL = 'ADMIN_ADD_ITEM_REQUEST_FAIL';
export const ADMIN_ADD_ITEM_RESET_STATE = 'ADMIN_ADD_ITEM_RESET_STATE';

export const ADMIN_UPDATE_ITEM_REQUEST = 'ADMIN_UPDATE_ITEM_REQUEST';
export const ADMIN_UPDATE_ITEM_REQUEST_STATUS =
  'ADMIN_UPDATE_ITEM_REQUEST_STATUS';
export const ADMIN_UPDATE_ITEM_REQUEST_SUCCESS =
  'ADMIN_UPDATE_ITEM_REQUEST_SUCCESS';
export const ADMIN_UPDATE_ITEM_REQUEST_FAIL = 'ADMIN_UPDATE_ITEM_REQUEST_FAIL';
export const ADMIN_UPDATE_ITEM_RESET_STATE = 'ADMIN_UPDATE_ITEM_RESET_STATE';

export const ADMIN_DELETE_ITEM_REQUEST = 'ADMIN_DELETE_ITEM_REQUEST';
export const ADMIN_DELETE_ITEM_REQUEST_STATUS =
  'ADMIN_DELETE_ITEM_REQUEST_STATUS';
export const ADMIN_DELETE_ITEM_REQUEST_SUCCESS =
  'ADMIN_DELETE_ITEM_REQUEST_SUCCESS';
export const ADMIN_DELETE_ITEM_REQUEST_FAIL = 'ADMIN_DELETE_ITEM_REQUEST_FAIL';

export const ADMIN_GET_ITEMS_REQUEST = 'ADMIN_GET_ITEMS_REQUEST';
export const ADMIN_GET_ITEMS_REQUEST_STATUS = 'ADMIN_GET_ITEMS_REQUEST_STATUS';
export const ADMIN_GET_ITEMS_REQUEST_SUCCESS =
  'ADMIN_GET_ITEMS_REQUEST_SUCCESS';
export const ADMIN_GET_ITEMS_REQUEST_FAIL = 'ADMIN_GET_ITEMS_REQUEST_FAIL';

export const ADMIN_GET_ITEM_DETAIL_REQUEST = 'ADMIN_GET_ITEM_DETAIL_REQUEST';
export const ADMIN_GET_ITEM_DETAIL_REQUEST_STATUS =
  'ADMIN_GET_ITEM_DETAIL_REQUEST_STATUS';
export const ADMIN_GET_ITEM_DETAIL_REQUEST_SUCCESS =
  'ADMIN_GET_ITEM_DETAIL_REQUEST_SUCCESS';
export const ADMIN_GET_ITEM_DETAIL_REQUEST_FAIL =
  'ADMIN_GET_ITEM_DETAIL_REQUEST_FAIL';

export const ADMIN_ADD_CATEGORY_REQUEST = 'ADMIN_ADD_CATEGORY_REQUEST';
export const ADMIN_ADD_CATEGORY_REQUEST_STATUS =
  'ADMIN_ADD_CATEGORY_REQUEST_STATUS';
export const ADMIN_ADD_CATEGORY_REQUEST_SUCCESS =
  'ADMIN_ADD_CATEGORY_REQUEST_SUCCESS';
export const ADMIN_ADD_CATEGORY_REQUEST_FAIL =
  'ADMIN_ADD_CATEGORY_REQUEST_FAIL';
export const ADMIN_ADD_CATEGORY_RESET_STATE = 'ADMIN_ADD_CATEGORY_RESET_STATE';

export const ADMIN_UPDATE_CATEGORY_REQUEST = 'ADMIN_UPDATE_CATEGORY_REQUEST';
export const ADMIN_UPDATE_CATEGORY_REQUEST_STATUS =
  'ADMIN_UPDATE_CATEGORY_REQUEST_STATUS';
export const ADMIN_UPDATE_CATEGORY_REQUEST_SUCCESS =
  'ADMIN_UPDATE_CATEGORY_REQUEST_SUCCESS';
export const ADMIN_UPDATE_CATEGORY_REQUEST_FAIL =
  'ADMIN_UPDATE_CATEGORY_REQUEST_FAIL';
export const ADMIN_RESET_CATEGORY = 'ADMIN_RESET_CATEGORY';

export const ADMIN_DELETE_CATEGORY_REQUEST = 'ADMIN_DELETE_CATEGORY_REQUEST';
export const ADMIN_DELETE_CATEGORY_REQUEST_STATUS =
  'ADMIN_DELETE_CATEGORY_REQUEST_STATUS';
export const ADMIN_DELETE_CATEGORY_REQUEST_SUCCESS =
  'ADMIN_DELETE_CATEGORY_REQUEST_SUCCESS';
export const ADMIN_DELETE_CATEGORY_REQUEST_FAIL =
  'ADMIN_DELETE_CATEGORY_REQUEST_FAIL';
export const ADMIN_DELETE_CATEGORY_RESET_STATE =
  'ADMIN_DELETE_CATEGORY_RESET_STATE';

export const ADMIN_GET_ORDERS_REQUEST = 'ADMIN_GET_ORDERS_REQUEST';
export const ADMIN_GET_ORDERS_REQUEST_STATUS =
  'ADMIN_GET_ORDERS_REQUEST_STATUS';
export const ADMIN_GET_ORDERS_REQUEST_SUCCESS =
  'ADMIN_GET_ORDERS_REQUEST_SUCCESS';
export const ADMIN_GET_ORDERS_REQUEST_FAIL = 'ADMIN_GET_ORDERS_REQUEST_FAIL';

export const ADMIN_GET_ORDER_DETAIL_REQUEST = 'ADMIN_GET_ORDER_DETAIL_REQUEST';
export const ADMIN_GET_ORDER_DETAIL_REQUEST_STATUS =
  'ADMIN_GET_ORDER_DETAIL_REQUEST_STATUS';
export const ADMIN_GET_ORDER_DETAIL_REQUEST_SUCCESS =
  'ADMIN_GET_ORDER_DETAIL_REQUEST_SUCCESS';
export const ADMIN_GET_ORDER_DETAIL_REQUEST_FAIL =
  'ADMIN_GET_ORDER_DETAIL_REQUEST_FAIL';

export const ADMIN_UPDATE_ORDER_REQUEST = 'ADMIN_UPDATE_ORDER_REQUEST';
export const ADMIN_UPDATE_ORDER_REQUEST_STATUS =
  'ADMIN_UPDATE_ORDER_REQUEST_STATUS';
export const ADMIN_UPDATE_ORDER_REQUEST_SUCCESS =
  'ADMIN_UPDATE_ORDER_REQUEST_SUCCESS';
export const ADMIN_UPDATE_ORDER_REQUEST_FAIL =
  'ADMIN_UPDATE_ORDER_REQUEST_FAIL';

export const ADMIN_GET_USERS_REQUEST = 'ADMIN_GET_USERS_REQUEST';
export const ADMIN_GET_USERS_REQUEST_STATUS = 'ADMIN_GET_USERS_REQUEST_STATUS';
export const ADMIN_GET_USERS_REQUEST_SUCCESS =
  'ADMIN_GET_USERS_REQUEST_SUCCESS';
export const ADMIN_GET_USERS_REQUEST_FAIL = 'ADMIN_GET_USERS_REQUEST_FAIL';
