export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_REQUEST_STATUS = 'USER_SIGNUP_REQUEST_STATUS';
export const USER_SIGNUP_REQUEST_SUCCESS = 'USER_SIGNUP_REQUEST_SUCCESS';
export const USER_SIGNUP_REQUEST_FAIL = 'USER_SIGNUP_REQUEST_FAIL';
export const USER_SIGNUP_RESET_STATE = 'USER_SIGNUP_RESET_STATE';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_REQUEST_STATUS = 'USER_SIGNIN_REQUEST_STATUS';
export const USER_SIGNIN_REQUEST_SUCCESS = 'USER_SIGNIN_REQUEST_SUCCESS';
export const USER_SIGNIN_REQUEST_FAIL = 'USER_SIGNIN_REQUEST_FAIL';
export const USER_SIGNIN_RESET_STATE = 'USER_SIGNIN_RESET_STATE';

export const USER_FORGOT_REQUEST = 'USER_FORGOT_REQUEST';
export const USER_FORGOT_REQUEST_STATUS = 'USER_FORGOT_REQUEST_STATUS';
export const USER_FORGOT_REQUEST_SUCCESS = 'USER_FORGOT_REQUEST_SUCCESS';
export const USER_FORGOT_REQUEST_FAIL = 'USER_FORGOT_REQUEST_FAIL';
export const USER_FORGOT_RESET_STATE = 'USER_FORGOT_RESET_STATE';

export const USER_RESET_REQUEST = 'USER_RESET_REQUEST';
export const USER_RESET_REQUEST_STATUS = 'USER_RESET_REQUEST_STATUS';
export const USER_RESET_REQUEST_SUCCESS = 'USER_RESET_REQUEST_SUCCESS';
export const USER_RESET_REQUEST_FAIL = 'USER_RESET_REQUEST_FAIL';
export const USER_RESET_RESET_STATE = 'USER_RESET_RESET_STATE';

export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';
