export const ADD_ORDER = 'ADD_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const REMOVE_FROM_ORDER = 'REMOVE_FROM_ORDER';
export const UPDATE_ORDER_PAYMENT_TYPE = 'UPDATE_ORDER_PAYMENT_TYPE';
export const UPDATE_ORDER_DELIVERY_ADDRESS = 'UPDATE_ORDER_DELIVERY_ADDRESS';
