export const GET_HOME_PAGE_DATA_REQUEST = 'GET_HOME_PAGE_DATA_REQUEST';
export const GET_HOME_PAGE_DATA_REQUEST_STATUS =
  'GET_HOME_PAGE_DATA_REQUEST_STATUS';
export const GET_HOME_PAGE_DATA_REQUEST_SUCCESS =
  'GET_HOME_PAGE_DATA_REQUEST_SUCCESS';
export const GET_HOME_PAGE_DATA_REQUEST_FAIL =
  'GET_HOME_PAGE_DATA_REQUEST_FAIL';

export const GET_MENU_PAGE_DATA_REQUEST = 'GET_MENU_PAGE_DATA_REQUEST';
export const GET_MENU_PAGE_DATA_REQUEST_STATUS =
  'GET_MENU_PAGE_DATA_REQUEST_STATUS';
export const GET_MENU_PAGE_DATA_REQUEST_SUCCESS =
  'GET_MENU_PAGE_DATA_REQUEST_SUCCESS';
export const GET_MENU_PAGE_DATA_REQUEST_FAIL =
  'GET_MENU_PAGE_DATA_REQUEST_FAIL';

export const GET_ITEM_DETAIL_REQUEST = 'GET_ITEM_DETAIL_REQUEST';
export const GET_ITEM_DETAIL_REQUEST_STATUS = 'GET_ITEM_DETAIL_REQUEST_STATUS';
export const GET_ITEM_DETAIL_REQUEST_SUCCESS =
  'GET_ITEM_DETAIL_REQUEST_SUCCESS';
export const GET_ITEM_DETAIL_REQUEST_FAIL = 'GET_ITEM_DETAIL_REQUEST_FAIL';

export const GET_CATEGORY_LIST_REQUEST = 'GET_CATEGORY_LIST_REQUEST';
export const GET_CATEGORY_LIST_REQUEST_STATUS =
  'GET_CATEGORY_LIST_REQUEST_STATUS';
export const GET_CATEGORY_LIST_REQUEST_SUCCESS =
  'GET_CATEGORY_LIST_REQUEST_SUCCESS';
export const GET_CATEGORY_LIST_REQUEST_FAIL = 'GET_CATEGORY_LIST_REQUEST_FAIL';
