export const USER_PLACE_ORDER_REQUEST = 'USER_PLACE_ORDER_REQUEST';
export const USER_PLACE_ORDER_REQUEST_STATUS =
  'USER_PLACE_ORDER_REQUEST_STATUS';
export const USER_PLACE_ORDER_REQUEST_SUCCESS =
  'USER_PLACE_ORDER_REQUEST_SUCCESS';
export const USER_PLACE_ORDER_REQUEST_FAIL = 'USER_PLACE_ORDER_REQUEST_FAIL';
export const RESET_USER_PLACE_ORDER = 'RESET_USER_PLACE_ORDER';

export const USER_UPDATE_ORDER_REQUEST = 'USER_UPDATE_ORDER_REQUEST';
export const USER_UPDATE_ORDER_REQUEST_STATUS =
  'USER_UPDATE_ORDER_REQUEST_STATUS';
export const USER_UPDATE_ORDER_REQUEST_SUCCESS =
  'USER_UPDATE_ORDER_REQUEST_SUCCESS';
export const USER_UPDATE_ORDER_REQUEST_FAIL = 'USER_UPDATE_ORDER_REQUEST_FAIL';
export const RESET_UPDATE_ORDER = 'RESET_UPDATE_ORDER';

export const USER_GET_ORDER_DETAIL_REQUEST = 'USER_GET_ORDER_DETAIL_REQUEST';
export const USER_GET_ORDER_DETAIL_REQUEST_STATUS =
  'USER_GET_ORDER_DETAIL_REQUEST_STATUS';
export const USER_GET_ORDER_DETAIL_REQUEST_SUCCESS =
  'USER_GET_ORDER_DETAIL_REQUEST_SUCCESS';
export const USER_GET_ORDER_DETAIL_REQUEST_FAIL =
  'USER_GET_ORDER_DETAIL_REQUEST_FAIL';
export const CLEAR_GET_ORDER_DETAIL_ERROR = 'CLEAR_GET_ORDER_DETAIL_ERROR';

export const USER_CANCEL_ORDER_REQUEST = 'USER_CANCEL_ORDER_REQUEST';
export const USER_CANCEL_ORDER_REQUEST_STATUS =
  'USER_CANCEL_ORDER_REQUEST_STATUS';
export const USER_CANCEL_ORDER_REQUEST_SUCCESS =
  'USER_CANCEL_ORDER_REQUEST_SUCCESS';
export const USER_CANCEL_ORDER_REQUEST_FAIL = 'USER_CANCEL_ORDER_REQUEST_FAIL';
export const CLEAR_CANCEL_ORDER_ERROR = 'CLEAR_CANCEL_ORDER_ERROR';

export const USER_UPDATE_DETAIL_REQUEST = 'USER_UPDATE_DETAIL_REQUEST';
export const USER_UPDATE_DETAIL_REQUEST_STATUS =
  'USER_UPDATE_DETAIL_REQUEST_STATUS';
export const USER_UPDATE_DETAIL_REQUEST_SUCCESS =
  'USER_UPDATE_DETAIL_REQUEST_SUCCESS';
export const USER_UPDATE_DETAIL_REQUEST_FAIL =
  'USER_UPDATE_DETAIL_REQUEST_FAIL';
export const USER_UPDATE_DETAIL_RESET_STATE = 'USER_UPDATE_DETAIL_RESET_STATE';

export const USER_GET_ORDERS_REQUEST = 'USER_GET_ORDERS_REQUEST';
export const USER_GET_ORDERS_REQUEST_STATUS = 'USER_GET_ORDERS_REQUEST_STATUS';
export const USER_GET_ORDERS_REQUEST_SUCCESS =
  'USER_GET_ORDERS_REQUEST_SUCCESS';
export const USER_GET_ORDERS_REQUEST_FAIL = 'USER_GET_ORDERS_REQUEST_FAIL';

export const USER_ADD_REVIEW_REQUEST = 'USER_ADD_REVIEW_REQUEST';
export const USER_ADD_REVIEW_REQUEST_STATUS = 'USER_ADD_REVIEW_REQUEST_STATUS';
export const USER_ADD_REVIEW_REQUEST_SUCCESS =
  'USER_ADD_REVIEW_REQUEST_SUCCESS';
export const USER_ADD_REVIEW_REQUEST_FAIL = 'USER_ADD_REVIEW_REQUEST_FAIL';
export const USER_CLEAR_REVIEW_STATE = 'USER_CLEAR_REVIEW_STATE';

export const USER_PAY_FOR_ORDER_REQUEST = 'USER_PAY_FOR_ORDER_REQUEST';
export const USER_PAY_FOR_ORDER_REQUEST_STATUS =
  'USER_PAY_FOR_ORDER_REQUEST_STATUS';
export const USER_PAY_FOR_ORDER_REQUEST_SUCCESS =
  'USER_PAY_FOR_ORDER_REQUEST_SUCCESS';
export const USER_PAY_FOR_ORDER_REQUEST_FAIL =
  'USER_PAY_FOR_ORDER_REQUEST_FAIL';
export const CLEAR_PAY_FOR_ORDER_ERROR = 'CLEAR_PAY_FOR_ORDER_ERROR';
export const RESET_USER_PAY_FOR_ORDER_REQUEST =
  'RESET_USER_PAY_FOR_ORDER_REQUEST';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_REQUEST_STATUS = 'UPLOAD_IMAGE_REQUEST_STATUS';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
export const UPLOAD_IMAGE_CLEAR_ERROR = 'UPLOAD_IMAGE_CLEAR_ERROR';
